name: Custom Rom Builder Samsung Galaxy A03
permissions:
  contents: write
on:
  push:
    branches:
      - main  # Change this to your desired branch
  workflow_dispatch:
    inputs:
        GSI:
              description: ' GSI Image Direct Link '
              required: true
              default: 'https://github.com/ponces/treble_build_aosp/releases/download/v2023.12.01/aosp-arm64-ab-gapps-14.0-20231201.img.xz'        
        NAME:
              description: 'Rom Name'
              required: true
              default: 'aosp-arm64-ab-gapps-14.0-a03.7z'
        VERSION:
              description: 'Baseband Version'
              required: true
              default: 'A035FXXU4CWI1'
        VENDOR:
              description: 'Enter Direct Link Of Your Version Vendor'
              required: true
              default: 'https://sourceforge.net/projects/a03-files/files/A035FXXU4CWI1/vendor.img'
jobs:
  Build:
    runs-on: ubuntu-latest

    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y zip xz-utils unzip p7zip-full wget
        
    - name: Installing Tools
      run: |
        git clone https://github.com/Exynos-nigg/lpunpack-lpmake-mirror.git lpbinary
        cd lpbinary
        bash install.sh
    - name: Preparing Files
      run: |
        cd lpbinary/binary
        wget ${{ github.event.inputs.VENDOR }}
        wget https://sourceforge.net/projects/a03-files/files/product.img
        wget https://sourceforge.net/projects/a03-files/files/system_ext.img
    - name: Downloading Your GSI And Extracting
      run: |
        cd lpbinary/binary
        wget ${{ github.event.inputs.GSI }}
        mkdir sys
        mv *.xz sys
        cd sys
        unxz *.xz
        mv *.img ../system.img
        cd ..
    - name: Packing
      run: |
        cd lpbinary/binary
        ./lpmake --metadata-size 65536 --super-name super --metadata-slots 2 --device super:6763315200 --group main:6761218048 --partition system:readonly:$(ls -nl system.img | awk '{print $5}'):main --image system=system.img --partition vendor:readonly:$(ls -nl vendor.img | awk '{print $5}'):main --image vendor=vendor.img --partition product:readonly:$(ls -nl product.img | awk '{print $5}'):main --image product=product.img --partition system_ext:readonly:$(ls -nl system_ext.img | awk '{print $5}'):main --image system_ext=system_ext.img --sparse --output super.img
    - name: Creating tar and compressing to 7z
      run: |
        cd lpbinary/binary
        tar -cvf super.tar super.img
        rm -rf super.img
        7z a ${{ github.event.inputs.NAME }} super.tar
        rm -rf super.tar
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: lpbinary/binary/${{ github.event.inputs.NAME }}
        name: ${{ github.event.inputs.NAME }}-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
            Device: Samsung Galaxy A03
            Version: ${{ github.event.inputs.VERSION }}
            Rom Name: ${{ github.event.inputs.NAME }}
            Flash: Extract the 7z file and flash through ODIN in AP Section.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }
